language : node_js

dist: trusty

node_js : 
   - "node"

services :
  - "postgresql"

addons: 
  postgresql: "10"
  apt:
    packages: 
    - postgresql-10 
before_script:
  - psql -c 'create database e-Manager;' -U postgres
  - cp database.yml.travis config/database.yml

  

COVERALLS_REPO_TOKEN: YtcddTyvMkCkdLZXWbcH3TjqmxeQp26Mg

