language : node_js
node_js: 'stable'
install:
  - npm install

script:
  - npm test
env:
  - NODE_ENV=test

cache:
  directories:
    - "node_modules"

services :
  - postgresql

before_script:
  - createuser tolu -s -U postgres
  - createdb database_test --username=tolu
  - sequelize db:migrate

