language : node_js

node_js : 
   - "node"

services :
  - "postgresql"

before_script:
  - psql -c "CREATE DATABASE e-Manager;" -U postgres
  - psql -c "CREATE USER postgres WITH PASSWORD 'opeyemi007';" -U postgres



COVERALLS_REPO_TOKEN: YtcddTyvMkCkdLZXWbcH3TjqmxeQp26Mg

