language : node_js

node_js : 
   - "node"

services :
  - "postgresql"

before_script:
  - psql --host=127.0.0.1 --port=5432 --username=postgres --password --dbname=e_Manager
 
addons: 
  postgresql: "10"
  apt:
    packages: 
    - postgresql-10 
    - postgresql-client-10
  

COVERALLS_REPO_TOKEN: YtcddTyvMkCkdLZXWbcH3TjqmxeQp26Mg

