language : node_js

node_js : 
   - "node"

services :
  - "postgresql"

before_script:
  - psql -c 'createdb e-Manager;'
  - cp config/database.yml.travis config/database.yml
addons: 
  postgresql: "10"
  apt:
    packages: 
    - postgresql-10 
    - postgresql-client-10
  

COVERALLS_REPO_TOKEN: YtcddTyvMkCkdLZXWbcH3TjqmxeQp26Mg

