language : node_js

node_js : 
   - "node"

services :
  - "postgresql"

addons: 
  postgresql: "10"
  apt:
    packages: 
    - postgresql-10 
    - postgresql-client-10

before_script:
  - psql -c 'createdb e-Manager;'
  - cp database.yml.travis config/database.yml

  

COVERALLS_REPO_TOKEN: YtcddTyvMkCkdLZXWbcH3TjqmxeQp26Mg

