language : node_js

node_js : 
   - "node"

services :
  - "postgresql"

before_script:
  - psql -c "CREATE DATABASE e-Manager;" -U postgres
  - psql -c "CREATE USER travis_test WITH PASSWORD 'opeyemi007';" -U postgres

addons: 
  postgresql: "10"
  apt:
    packages: 
    - postgresql-10 
  

COVERALLS_REPO_TOKEN: YtcddTyvMkCkdLZXWbcH3TjqmxeQp26Mg

