language : node_js

dist: trusty

node_js : 
   - "node"

services :
  - "postgresql"

addons: 
  postgresql: "10"
  apt:
    packages: 
    - postgresql-10 
script:
  - npm run test


  

COVERALLS_REPO_TOKEN: YtcddTyvMkCkdLZXWbcH3TjqmxeQp26Mg

